services:
  - type: web
    name: google-form-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com  # 🔁 Update after frontend is deployed
