services:
  - type: web
    name: google-form-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=8000
    runtime: python
    pythonVersion: 3.10  # ✅ Important fix to avoid Python 3.13 error
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-url.onrender.com  # ✅ Change this after frontend deployment
