services:
  - type: web
    name: google-form-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host=0.0.0.0 --port=8000
    envVars:
      - key: MONGODB_URI
        sync: false   # Prevents storing the value in version control
      - key: FRONTEND_URL
        value: http://localhost:3000
